### ISSUE TITLE
Request for Assistance with XRP Loss Due to Spread – Possible Refund or Resolution?

### ISSUE THREAD

**Issue by Paulpegasus123** [r0bertz/xrpl-order-toolkit#1]
Hello,

I recently used the XRP Toolkit and encountered an issue where I accidentally sold my XRP for another currency and then tried to buy it back a few seconds later. Due to a significant spread, I received only a fraction of the XRP I had originally sold, resulting in a substantial loss.

I understand that spreads can vary in the cryptocurrency market, but I would like to know if there is any way to **recover part of the loss** or if there are any options for a **refund** or resolution in such cases.

Here are the transaction details:
- **Amount of XRP sold**: 245.463 XRP
- **Amount of XRP received upon buying back**: 0.3293 XRP
- **Time of transaction**: 	Dec 02, 2024 at 10:27:21 PM UTC
- **Spread difference observed**: I observed that the difference between the time I sold my XRP and the time I bought it back was **over 99%**. This resulted in receiving only **0.3293 XRP** when I originally sold **245.463 XRP**, leading to a substantial loss.

Could anyone assist me with how to proceed, or if there are any steps to take to potentially resolve this situation?

Thank you for your time and support.

Best regards,  
Paul

**Comment by r0bertz** [comment]
Sorry for your loss. But there's no way to revert that. Always test with infinitesimal amount first.
